image: Ubuntu 

stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - java -jar ./artifacts/app-card-delivery.jar -port=9999 &
  - - chmod +x gradlew

build_script:
  - ./gradlew test -Dselenide.headless=true --info